# These values are custom to override the default ones
replicaCount: 1

image:
  repository: ghcr.io/willemsbrecht/mlops_lab_01-fastapi
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

nodeSelector:
  kubernetes.io/hostname: willems-brecht
